//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheet.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string DOB { get; set; }
        public string MaritalStatus { get; set; }
        public string AnniversaryDate { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public string Experience { get; set; }
        public string ReportingTo { get; set; }
        public string Email { get; set; }
        public string JoiningDate { get; set; }
        public string RoleId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
