//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheet.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDetail
    {
        public string ProjectKey { get; set; }
        public string Name { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> AllottedHours { get; set; }
        public string MobileNumber { get; set; }
        public string ClientName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string DomainName { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ClientCoordinatorName { get; set; }
        public string ClientCoordinatorMobileNumber { get; set; }
        public string ClientCoordinatorEmail { get; set; }
    }
}
