//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheet.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkDetail
    {
        public string WorkDetailId { get; set; }
        public string EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string ProjectName { get; set; }
        public string Hours { get; set; }
        public string Remarks { get; set; }
        public string Date { get; set; }
        public string WorkProjectName { get; set; }
        public string Minutes { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
    }
}
